@VAULT_TOKEN=1f91d80e-0a03-49b3-b84b-f1de3d172eec
@MICROSOFT_FOUNDRY_KEY1=CHAVE_MICROSOFT_FOUNDRY
@APISIX_ADMIN_KEY=edd1c9f034335f136f87ad84b625c8f1

###
# Passo 1: Crie aqui um mount para o Vault do APISIX
curl "http://127.0.0.1:1337/v1/sys/mounts/apisix" -X POST \
  -H "X-Vault-Token: {{VAULT_TOKEN}}" \
  -H "Content-Type: application/json" \
  -d '{
    "type": "kv",
    "options": {
      "version": "1"
    }
  }'

###
# Passo 2: Criar secret para o vault do APISIX com a chave do Microsoft Foundry
curl "http://127.0.0.1:1337/v1/apisix/foundry" -X POST \
  -H "X-Vault-Token: {{VAULT_TOKEN}}" \
  -H "Content-Type: application/json" \
  -d '{
      "key1": "{{MICROSOFT_FOUNDRY_KEY1}}"
  }'


###
# Passo 3: Consultar o Secret criado no Vault do APISIX
curl "http://127.0.0.1:1337/v1/apisix/foundry" -X GET \
  -H "X-Vault-Token: {{VAULT_TOKEN}}"

###
# Passo 4: Configurar Vault para uso no APISIX
curl http://127.0.0.1:9180/apisix/admin/secrets/vault/1 \
  -H "X-API-KEY: {{APISIX_ADMIN_KEY}}" -X PUT -d '
{
    "uri": "http://openbao-dev:1337",
    "prefix": "apisix",
    "token": "{{VAULT_TOKEN}}"
}'


###
# Passo 5: Consultar a configuração do Vault no APISIX
curl "http://127.0.0.1:9180/apisix/admin/secrets/vault/1" -X GET \
  -H "X-API-KEY: {{APISIX_ADMIN_KEY}}"